apiVersion: apps/v1
kind: Deployment
metadata:
    name: strava-nginx-deplo
    namespace: pre
spec:
   replicas: 1
   selector:
      matchLabels:
         app: strava-nginx-deplo
   template:
     metadata:
        labels:
          app: strava-nginx-deplo
     spec:
        containers:
        - name: mpg-vue
          image: mpastorg/mpg-vuejs:$RELEASE.$BUILD_NUMBER
          imagePullPolicy: Always
          ports:
          - containerPort: 443
            containerPort: 80
          volumeMounts:
          - name: cm-app-nginx-vol
            mountPath: "/etc/nginx/conf.d/"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
              memory: 512Mi
        nodeSelector:
          kubernetes.io/arch: amd64
        volumes:
          - name: cm-app-nginx-vol
            configMap:
              name: cm-app-nginx-7k222k6t9g
              items:
              - key: default.conf
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: strava-nginx-svc
  name: strava-nginx-svc
  namespace: pre
spec:
  ports:
  ports:
  - name: http
    port: 80
    nodePort: 32209
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    nodePort: 32206
    protocol: TCP
    targetPort: 443
  selector:
    app: strava-nginx-deplo
  sessionAffinity: None
  type: NodePort