pipeline {
  agent any
  environment {
    ENV = 'pro'
    HTTP_PORT = '32509'
    HTTPS_PORT = '32506'
    RELEASE = '0.4'
    registry = "mpastorg/mpg-vuejs"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  stages {
    stage('Deploy on kubernetes') {
      steps {
          kubernetesDeploy(
              kubeconfigId: '1c99e9a6-3159-41f1-a7d3-2e4dbbe13455',
              configs: 'strava-nginx-deplo.yml',
              enableConfigSubstitution: true
          )
      }
    }
  }
}
